### ISSUE TITLE
📁Docs: Add light mode for docs site?

### ISSUE THREAD

**Issue by isunjn** [melt-ui/melt-ui#512]
Dark mode is cool, but light mode is essential for a daily-basis docs site.

**Comment by TGlide** [comment]
Yes, I do want to add it :)

**Comment by goswamianshuman** [comment]
@TGlide Hey Thomas, Can I work on it?😃

**Comment by mustafa0x** [comment]
melt ui is awesome; thanks.

agreed; dark mode leaves me disoriented. I found these styles get me 80% there.

```css
body {
  background: #fff;
  color: #333;
}
.text-neutral-100 {
  color: #888;
}
.\!bg-neutral-800\/50 {
  background-color: #000 !important;
}
```
